export const PRODUCT_GETREQUEST_PENDING = "PRODUCT_GETREQUEST_PENDING";
export const PRODUCT_GETREQUEST_SUCCESS = "PRODUCT_GETREQUEST_SUCCESS";
export const PRODUCT_GETREQUEST_FAILURE = "PRODUCT_GETREQUEST_FAILURE";
export const UPDATE_PATH = "UPDATE_PATH";
export const TOTAL_ITEMS = "TOTAL_ITEMS";