import my_border from "../scripts/my_border";
import my_pixel from "../scripts/my_pixel";
import {
  ALL_DISCOUNT,
  AVAILABILITY,
  BRAND,
  COLLAR,
  COLORS_TYPES,
  COLOUR,
  DISCOUNT,
  FABRIC_FAMILY,
  FEATURES,
  FEATURES_TYPES,
  FIT,
  OCCASION,
  PATTERN,
  PRICE,
  RATINGS,
  RATINGS_TYPES,
  SIZE,
  SIZES_TYPES,
  TYPE,
} from "./constants";
import {
  FILL_10PARENT,
  FILL_PARENT,
  RED,
  SOLID,
  WHEAT,
  WHITE,
  AUTO,
} from "./typography";

export const circularCategoryData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46012802433054.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "menswear",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46012802367518.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "shoes",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46012802564126.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "womenswear",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46012802629662.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "gadgets",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46131531546654.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "beauty",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46012802695198.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "home",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45548090884126.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46131534299166.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "westside",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46012802826270.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "kid'swear",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46012802760734.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "watches",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/46012802891806.jpg",
    w: AUTO,
    h: AUTO,
    bs: "",
    border: "",
    br: 0,
    category: "jewellery",
  },
];

export const bankImageData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45103367290910.jpg",
    w: my_pixel(350),
    h: my_pixel(80),
    bs: "",
    border: my_border(1, SOLID, WHEAT),
    br: 6,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45433290981406.jpg",
    w: my_pixel(350),
    h: my_pixel(80),
    bs: "",
    border: my_border(1, SOLID, WHEAT),
    br: 6,
    category: "",
  },
];

export const dealsWheelData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45539109175326.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "shoes",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45539107635230.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "womenswear",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536789692446.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "menswear",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536789954590.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const newOnCliqData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45587495813150.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581157761054.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581157826590.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45567395594270.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const featuredBrandData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45587477364766.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45423735734302.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45587477430302.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45587477495838.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const popularpiqsData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45576213397534.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581156089886.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581156155422.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581156220958.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const womensWearData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45382586564638.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45382586630174.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45435992703006.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45382586761246.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const trendingNowData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584580378654.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584580313118.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584586997790.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584587063326.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584587325470.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584587391006.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584587456542.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584587522078.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const mensWearByCliqData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584575987742.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584580313118.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584576118814.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584576184350.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584576446494.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584576512030.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45554447581214.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45584576708638.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const shoesData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581153566750.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581153632286.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581153697822.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581153763358.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581153959966.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581154222110.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581154287646.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45581153894430.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const westSideData = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536787726366.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536791330846.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536791396382.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536791461918.jpg",
    w: AUTO,
    h: "",
    bs: "",
    border: "",
    br: 4,
    category: "",
  },
];

export const FilterData = [
  {
    name: SIZE,
    options: SIZES_TYPES,
  },
  {
    name: COLOUR,
    options: COLORS_TYPES,
  },
  {
    name: RATINGS,
    options: RATINGS_TYPES,
  },
  {
    name: FEATURES,
    options: FEATURES_TYPES,
  },
  {
    name: BRAND,
    options: [],
  },
  {
    name: PRICE,
    options: [],
  },
  {
    name: DISCOUNT,
    options: [],
  },
  {
    name: TYPE,
    options: [],
  },
  {
    name: FABRIC_FAMILY,
    options: [],
  },
  {
    name: PATTERN,
    options: [],
  },
  {
    name: FIT,
    options: [],
  },
  {
    name: COLLAR,
    options: [],
  },
  {
    name: OCCASION,
    options: [],
  },
  {
    name: ALL_DISCOUNT,
    options: [],
  },
  {
    name: AVAILABILITY,
    options: [],
  },
];

export const dummyImages1 = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45539109339166.jpg",
    alt: "Image 1",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45539109175326.jpg",
    alt: "Image 2",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536789692446.jpg",
    alt: "Image 3",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45539107635230.jpg",
    alt: "Image 4",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45536789954590.jpg",
    alt: "Image 5",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45588212875294.jpg",
    alt: "Image 6",
  },
];

export const dummyImages2 = [
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45717766963230.jpg",
    alt: "Image 1",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45717767028766.jpg",
    alt: "Image 2",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45717767094302.jpg",
    alt: "Image 3",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45717767159838.jpg",
    alt: "Image 4",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45727710183454.jpg",
    alt: "Image 5",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45717767421982.jpg",
    alt: "Image 6",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45717767487518.jpg",
    alt: "Image 7",
  },
  {
    src: "https://assets.tatacliq.com/medias/sys_master/images/45717767553054.jpg",
    alt: "Image 8",
  },
];
